### ISSUE TITLE
How to test on a single image?

### ISSUE THREAD

**Issue by cyberdecker** [tum-vision/captcha_recognition#1]
After training the network using your scripts, I have adapted the code test_network to test a single image, as in the file [here](https://gist.github.com/cyberdecker/3d358ab9166f57892e2d713942c1bd30). But I always get the following error:

`
F0506 09:44:28.992152  8514 net.cpp:829] Cannot copy param 0 weights from layer 'ip1'; shape mismatch.  Source param shape is 3072 28800 (88473600); target param shape is 3072 16896 (51904512). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
[1]    8514 abort (core dumped)  python simpletest.py
`

I'm using the same prototxt (network_captchas_with_3_convolutional_layers), and the image have a 180x50 size, but I don't get past this error. I assume that is some error on input, but how to solve this?

Thanks!

**Comment by BlackFlying** [comment]
I suggest you read his code named test_network.py.  
I did not meet your question. I met the result is so low  ，the max is 1.95%.and the more i train,the lower result i get.

**Comment by demolitionfabi** [comment]
Can you paste the full output log that you get?
I had a look at your code and for me it should work like this.
Can you also please double check again that the image that you want to classify really has a resolution of 180 x 50 and also that the images in your training lmdb really have a dimenstion of 180 x 50?
I think something like this should work to double check the latter:

```
import sys
sys.path.insert(0, './python')
import caffe

import numpy as np
import matplotlib.pyplot as plt
# display plots in this notebook
%matplotlib inline

# for reading lmdb
import lmdb
import caffe.proto.caffe_pb2
from caffe.io import datum_to_array

lmdb_dirname = '…'

# Open LMDB
lmdb_env = lmdb.open(lmdb_dirname)
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()

datum = caffe.proto.caffe_pb2.Datum()

for key, value in lmdb_cursor:
    datum.ParseFromString(value)
    #label = datum.label
    imagefile = caffe.io.datum_to_array(datum)

    imagefile = np.transpose(imagefile, (1, 2, 0))
    #plt.imshow(imagefile / 255)
    print imagefile.shape
    break
```

**Comment by cyberdecker** [comment]
Thanks for the code! I have resolved the issue, I double checked and discovered that the size in the training lmdb was not 180x50, so the network was trained in another size.

**Comment by muhakbaryasin** [comment]
@BlackFlying It's confusing. Mine too.
