### ISSUE TITLE
My test result start from about 0.9% correctness and going lower on the next epoch

### ISSUE THREAD

**Issue by muhakbaryasin** [tum-vision/captcha_recognition#7]
The first epoch is about 0.9% - 1% correctness but on the next epoch  it's going lower.  It's only 4 epoch so far. On the 5th epoch, the program gave me some error log while training and affecting to next next epoch. Which I want to figure out later. So I've not reach the max epoch (which is 45).

But, regarding my result at first epoch which is only about 0.9% - 1% correctness and going lower at the next 3 epoch, is it possibly missconfiguration or do I miss something? 

Forked repo
https://github.com/muhakbaryasin/captcha_recognition

Thank you.

**Comment by zhiweichen0012** [comment]
I also meet the problem, and feel puzzled, maybe you can try the mode "wrong_mostuncertain", "wrong_mostcertain" or "wrong_random", then you could see the result which is similar to author's.
like this:(run in "wrong_random" mode  )
5000: 0.00%
10000: 0.40%
15000: 1.90%
20000: 2.75%
25000: 3.00%
30000: 2.45%
35000: 3.60%
40000: 3.50%
45000: 2.65%
50000: 1.55%
55000: 13.30%
60000: 18.65%
65000: 18.15%
70000: 20.55%
75000: 22.10%
80000: 31.55%
85000: 33.75%
90000: 35.50%
95000: 34.55%
100000: 34.95%

Hope to help you.

**Comment by muhakbaryasin** [comment]
Arigatou gozaimasyu @zhiweichen12. I will try those modes. So much helped
